name: "FusionSolar MQTT Bridge"
version: "1.1.4"
slug: "fusionsolar"
description: "Fetch Huawei FusionSolar data and publish to MQTT for Home Assistant"
url: "https://github.com/ihkawiss/fusion-solar-api-ha"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: application
boot: auto
hassio_api: true
hassio_role: default
options:
  fusionsolar_username: ""
  fusionsolar_password: ""
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  poll_interval_minutes: 1
  station_dn: "NE=XXXXXXXXXXXX"
schema:
  fusionsolar_username: str
  fusionsolar_password: password
  mqtt_host: str
  mqtt_port: port
  mqtt_username: str?
  mqtt_password: password?
  poll_interval_minutes: int(1,60)
  station_dn: str
